name: FalchusLib
version: ${project.version}
description: A simple library.
main: com.falchus.lib.minecraft.spigot.FalchusLibMinecraftSpigot
author: Falchus
website: lib-java.falchus.com

load: startup
softdepend: [LuckPerms]